import "./styles/globals.css";
import "./styles/styles.css";
import "./styles/animations.css";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { ChatWrapper } from "./contexts/ChatContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "chatbot",
  description: "generated by anthony urbina",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <head>
        <link href='https://cdn.jsdelivr.net/npm/remixicon@3.4.0/fonts/remixicon.css' rel='stylesheet' />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
